### ISSUE TITLE
midisound not compiling with mingw

### ISSUE THREAD

**Issue by FrankR59** [lenmus/wxmidi#5]
In lines 685 and 705 I get the following errors from GNU GCC Compiler:
error: cast from 'void*' to 'long int' loses precision [-fpermissive]
error: cast from 'void*' to 'long int' loses precision [-fpermissive]

Those lines are:
int nMidiDev = reinterpret_cast<long>( m_pOutCombo->GetClientData(nIndex) );
...
nMidiDev = reinterpret_cast<long>( m_pInCombo->GetClientData(nIndex) );

**Comment by FrankR59** [comment]
A workaround seems to be:
for line 685:
`int nMidiDev = m_pOutCombo->GetCurrentSelection();`

and for line 705:
`nMidiDev = m_pOutCombo->GetCurrentSelection();`

as "GetClientData" seems to be depracted in wxWidget 3.2.
Not sure is this really works ...

**Comment by cecilios** [comment]
Sorry for the delay. I was very bussy this week.
The lines were you get the error are in fact:
https://github.com/lenmus/wxmidi/blob/3dadde2249d41a2aedfe05b923bdb63ef92bee6c/samples/midisound/midisound.cpp#L685

https://github.com/lenmus/wxmidi/blob/3dadde2249d41a2aedfe05b923bdb63ef92bee6c/samples/midisound/midisound.cpp#L705

So probably the error is casting a long to an int but I can not reproduce the error using GCC.

Probably your fix work properly.  The midi device number (an int) is saved in the combobox as client data by casting it to a void*. So when it is recovered by `GetClientData` it must be cast back to an int.

>...  as "GetClientData" seems to be depracted in wxWidget 3.2.

Uhm! Not sure about that! I can not find any reference to this being deprecated and it is still available in the documenttaion for wxWidgets 3.3, see https://docs.wxwidgets.org/trunk/classwx_item_container.html . Deprecating these methods will have a great impact in wxWidgets users as it is a widely used method. Could you please give me more information about the deprecation of these methods?

In any case, being deprecated doesn't mean that they do not work, but that they are still supported but you should not use it as in a future it could be removed. Therefore, current code will work perfectly.

I'm still using wxWidgets 3.0 and have not tried to compile this sample with newer wxWidgets versions so the sample is not updated

**Comment by FrankR59** [comment]
Hi, no problem.
Sorry for assuming that "GetClientData" was deprecated. I missed to look into the docs for "wxItemContainer", only read the docs for "wxComboBox".

Maybe there's a difference between our compilers. Which version of gcc do you use? I am on g++.exe 8.1.0 (built by MinGW-W64 project) running on Win11 and a Win10 machine.

I can probably switch to v10.0.0 and try again.

**Comment by cecilios** [comment]
I'm using gcc 7.5.0 running on Linux Mint 19. Not the latest but I prefer to have an stable system. In a couple of months I will have to move to 20 (Ubuntu 20.04 LTS) or better, to 21 (Ubuntu 22.04 LTS. And Ubuntu 22.04 LTS will install gcc-12 but will still be with wxWidgets 3.0 (https://repology.org/project/wxwidgets/versions)

**Comment by FrankR59** [comment]
There is no change in behavior when using the newest MinGW 12. But everything works fine when I change from
`reinterpret_cast<long>`
to 
`reinterpret_cast<long long>`

**Comment by cecilios** [comment]
Makes sense to me. The code dates back from 32 bits machines. In 64 bits machines a pointer is 64 bits. So when casting an `int` to `void*` and later casting it back to int, the first step is casting the pointer to a 64 bits integer and, thus, to `long long`.   In my machine with gcc 7.5.0 it also works. 

I would have expected that `reinterpret_cast<int>` should have worked, as but  in my machine with gcc 7.5.0 I get `error: cast from ‘void*’ to ‘int’ loses precision [-fpermissive]`. But, there is also the very same lost of precision in the assignment `int nMidiDev = reinterpret_cast<long long>(...)`  and the compiler does not complain. I do not understand the reason.

I will  change in the code to `reinterpret_cast<long long>`.

**Comment by FrankR59** [comment]
> I would have expected that `reinterpret_cast<int>` should have worked, as but in my machine with gcc 7.5.0 I get `error: cast from ‘void*’ to ‘int’ loses precision [-fpermissive]`. But, there is also the very same lost of precision in the assignment `int nMidiDev = reinterpret_cast<long long>(...)` and the compiler does not complain. I do not understand the reason.

Same here. Before I changed to long long I had the same idea changing to `reinterpreat_cast<int>` but my compiler complains with the same message as yours. 

> I will change in the code to `reinterpret_cast<long long>`.

Thanks very much!

**Comment by cecilios** [comment]
Fixed with commit  1f1bf5a247429ec9b96e45fb04a0271bcfb14afc
